(test
 (name test)
 (modules test)
 (libraries ecosystems ecosystems.client eio_main))

(test
 (name test_pages)
 (modules test_pages)
 (libraries ecosystems.client))

(test
 (name test_decode)
 (modules test_decode)
 (deps
  (glob_files fixtures/*.json))
 (libraries ecosystems openapi jsont))

(test
 (name test_http)
 (modules test_http)
 (libraries ecosystems ecosystems.client openapi fetch-curl eio_main))
