(library
 (name loopback)
 (modules loopback)
 (libraries eio))

(test
 (name test)
 (modules test)
 (libraries ecosystems ecosystems.client eio_main))

(test
 (name test_pages)
 (modules test_pages)
 (libraries ecosystems.client))

(test
 (name test_decode)
 (modules test_decode)
 (deps
  (glob_files fixtures/*.json))
 (libraries ecosystems openapi jsont))

(test
 (name test_http)
 (modules test_http)
 (libraries ecosystems ecosystems.client loopback openapi fetch-curl eio_main))

(test
 (name test_cli)
 (package ecosystems-cli)
 (modules test_cli)
 (deps
  (glob_files fixtures/*.json))
 (libraries ecosystems ecosystems_cli loopback openapi jsont eio_main))
