(test
 (name test_static)
 (modules test_static)
 (libraries proffer))

(test
 (name test_auth)
 (modules test_auth)
 (libraries arod.handlers))

(test
 (name test_base64)
 (modules test_base64)
 (libraries base64))

(test
 (name test_htmlit)
 (modules test_htmlit)
 (libraries htmlit))

(test
 (name test_ptime)
 (modules test_ptime)
 (libraries ptime ptime.clock))

(test
 (name test_uriz)
 (modules test_uriz)
 (libraries uriz))

(test
 (name test_feed_annotations)
 (modules test_feed_annotations)
 (libraries arod sortal.feed syndic uriz))

(test
 (name test_routes)
 (modules test_routes)
 (libraries arod arod.handlers arod.server proffer proffer.mock))
