(* Adapted from oi ca8c59ff, lib/cmd/makefile_export.ml, ISC. *)
(* Render a unified d10ir plan as a portable Makefile. See the .mli. The
   Makefile is a pure projection of {!Plan.t}; the per-node build
   logic lives in two emitted POSIX shell helpers so Make never has to
   quote a multi-line opam build script. *)

let ( / ) = Filename.concat
let lh = Layer_hash.to_string

type config_var = string * string * string

(* -- tiny fs helpers ---------------------------------------------------- *)

let rec mkdir_p d =
  if d <> "" && d <> "/" && d <> "." && not (Sys.file_exists d) then (
    mkdir_p (Filename.dirname d);
    try Unix.mkdir d 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ())

let write ?(mode = 0o644) path s =
  mkdir_p (Filename.dirname path);
  Out_channel.with_open_bin path (fun oc -> Out_channel.output_string oc s);
  try Unix.chmod path mode with Unix.Unix_error _ -> ()

(* -- embedded shell helpers (fixed; parameterised at run time) ---------- *)

let build_node_sh =
  {sh|#!/bin/sh
# Generated by D10ir.Makefile. Reproduces one Direct node
# build. Sources are pre-unpacked into sources/<sha>/ at emit time, so
# no network/curl/tar is needed at make time. Do not edit.
set -eu
# Paths must be ABSOLUTE: the sentinel->staging rebase feeds them to
# package configure scripts (e.g. OCaml's `configure --prefix`) that
# reject relative directories, and d10ir itself always stages into an
# absolute path.
DIST="${DIST:-src}"
ROOT="$(pwd)"            # output dir: holds the pre-unpacked sources/
case "$DIST" in /*) ;; *) DIST="$(pwd)/$DIST" ;; esac
RECIPES="$(pwd)/recipes"

H="$1"; SHA="$2"; shift 2   # rest: transitive dep layer hashes
# ONE invariant prefix for EVERY node (mirrors d10ir's relocatable
# layers). The sentinel is rebased to the same absolute path for all
# nodes, so a dependency's installed config (findlib.conf, *.config,
# wrapper scripts, ld.conf) stays valid when restaged into a consumer.
# A per-node prefix would bake a now-deleted path into those files.
# Cost: a shared prefix forces a serial build (Makefile sets
# .NOTPARALLEL); the per-package layer dirs are still produced.
PREFIX="$DIST/prefix"
BD="$DIST/build/$H"; LAYER="$DIST/layers/$H"; SNAP="$DIST/.snap/$H"
SENT="$(cat "$RECIPES/$H.prefix")"
NAME="$(cat "$RECIPES/$H.name")"
rebase() {
  # .build and .opam are producer sentinels, resolved before the prefix.
  escaped_prefix=$(printf '%s' "$PREFIX" | sed 's/[&\\#]/\\&/g')
  escaped_build=$(printf '%s' "$BD" | sed 's/[&\\#]/\\&/g')
  escaped_opam=$(printf '%s' "$ROOT/metadata/$NAME.opam" | sed 's/[&\\#]/\\&/g')
  sed -e "s#$SENT/\\.build#$escaped_build#g" \
      -e "s#$SENT/\\.opam-dir/opam#$escaped_opam#g" \
      -e "s#$SENT#$escaped_prefix#g" | sed -f "$BD/.d10-config.sed"
}

# Per-node logging: a tool like dune writes almost everything to
# stderr, so to actually keep the terminal to just the "BUILD <pkg>"
# line both streams go to src/log/<H>.log. On failure the log tail is
# pushed back to the real terminal (errors still come "to the fore").
# `make V=1` streams everything live instead.
LOG="$DIST/log/$H.log"; mkdir -p "$DIST/log"; : > "$LOG"
if [ "${V:-}" != 1 ]; then
  exec 3>&2                  # keep the real terminal for failure output
  exec >>"$LOG" 2>&1         # stdout+stderr -> per-node logfile
  trap 'rc=$?; if [ "$rc" -ne 0 ]; then { echo "d10: $NAME FAILED (exit $rc) — see $LOG; tail:"; tail -n 40 "$LOG"; } >&3; fi' EXIT
fi

# 1. Stage_deps: rebuild the prefix from this node's transitive dep layers
rm -rf "$PREFIX" "$BD" "$LAYER"; mkdir -p "$BD" "$LAYER" "$DIST/.snap"
for sub in bin sbin lib/stublibs lib/toplevel share man etc doc; do
  mkdir -p "$PREFIX/$sub"
done
for d in "$@"; do
  [ -d "$DIST/layers/$d" ] && cp -a "$DIST/layers/$d/." "$PREFIX/" || true
done

# 2. Unpack source: every input is a pre-unpacked tree under
#    $ROOT/sources/<sha>/ (unpacked archives) or $ROOT/<sha>/ (the local snapshot at $ROOT/source/,
#    sha="source"). No fetch, no decompress at make time.
if [ -d "$ROOT/sources/$SHA" ]; then
  cp -a "$ROOT/sources/$SHA/." "$BD/"
elif [ -d "$ROOT/$SHA" ]; then
  cp -a "$ROOT/$SHA/." "$BD/"
else
  echo "d10: no source for $SHA ($ROOT/sources/$SHA/ or $ROOT/$SHA/)" >&2
  exit 1
fi

# Resolve scalar opam configuration values from the installed dependencies.
: > "$BD/.d10-config.sed"
while IFS='|' read -r token file variable; do
  [ -n "$token" ] || continue
  value=$(awk -v key="$variable" '
    /^variables[[:space:]]*\{/ { invars=1; next }
    invars && /^}/ { invars=0 }
    invars {
      line=$0; sub(/^[[:space:]]*/, "", line)
      field=line; sub(/:.*/, "", field)
      if (field != key) next
      sub(/^[^:]*:[[:space:]]*/, "", line)
      sub(/[[:space:]]*$/, "", line)
      if (line ~ /^"[^"\\]*"$/) { sub(/^"/, "", line); sub(/"$/, "", line) }
      else if (line !~ /^(true|false|-?[0-9]+)$/) exit 2
      # Values are interpolated into already quoted shell arguments.
      if (index(line, sprintf("%c", 39))) exit 2
      print line; found=1; exit
    }
    END { if (!found) exit 2 }
  ' "$PREFIX/$file") || {
    echo "d10: missing or unsupported configuration $file:$variable" >&2
    exit 1
  }
  escaped=$(printf '%s' "$value" | sed 's/[&\\#]/\\&/g')
  printf 's#%s#%s#g\n' "$token" "$escaped" >> "$BD/.d10-config.sed"
done < "$RECIPES/$H.configvars"

# 3. Apply_substs: <base>.in -> <base>, %{var}% from substvars (rebased)
if [ -s "$RECIPES/$H.substs" ]; then
  while IFS= read -r base; do
    [ -n "$base" ] && [ -f "$BD/$base.in" ] || continue
    cp "$BD/$base.in" "$BD/$base"
    while IFS= read -r kv; do
      [ -n "$kv" ] || continue
      k=${kv%%=*}; v=${kv#*=}
      v=$(printf '%s' "$v" | rebase)
      esc=$(printf '%s' "$v" | sed 's/[&/\\]/\\&/g')
      t=$(mktemp); sed "s/%{$k}%/$esc/g" "$BD/$base" > "$t"; mv "$t" "$BD/$base"
    done < "$RECIPES/$H.substvars"
    rebase < "$BD/$base" > "$BD/$base.d10-subst"
    mv "$BD/$base.d10-subst" "$BD/$base"
  done < "$RECIPES/$H.substs"
fi

# 4. Snapshot_pre: record names, and a time marker so the layer also
#    captures dep files this node modifies IN PLACE (ld.conf etc.),
#    not just newly-named paths.
( cd "$PREFIX" && find . -mindepth 1 2>/dev/null | sed 's#^\./##' | LC_ALL=C sort ) > "$SNAP.before"
: > "$SNAP.stamp"

# 5. Run_script: /bin/sh -e -c SCRIPT from the unpacked source root
SCRIPT="$(rebase < "$RECIPES/$H.sh")"
NODEPATH=""
set --
while IFS= read -r kv; do
  [ -n "$kv" ] || continue
  case "$kv" in
    PATH=*) NODEPATH=$(printf '%s' "${kv#PATH=}" | rebase) ;;
    *) k=${kv%%=*}; v=$(printf '%s' "${kv#*=}" | rebase); set -- "$@" "$k=$v" ;;
  esac
done < "$RECIPES/$H.env"
FINALPATH="${NODEPATH:+$NODEPATH:}${PATH}"
( cd "$BD" && env -i HOME="${HOME:-/tmp}" TMPDIR="${TMPDIR:-/tmp}" PATH="$FINALPATH" \
    OCAMLFIND_LDCONF=ignore OI_STATIC="${OI_STATIC:-0}" "$@" /bin/sh -e -c "$SCRIPT" )

# 6. Apply_install_file (only when a static <name>.install was shipped)
[ -f "$BD/$NAME.install" ] && ./d10-install.sh "$BD" "$PREFIX" "$BD/$NAME.install" "$NAME"

# 7+8. Diff_layer + Store_layer: this node's additions (new names) UNION
#      its in-place modifications (mtime newer than the pre-run marker).
( cd "$PREFIX" && find . -mindepth 1 2>/dev/null | sed 's#^\./##' | LC_ALL=C sort ) > "$SNAP.after"
{ comm -13 "$SNAP.before" "$SNAP.after"
  ( cd "$PREFIX" && find . -mindepth 1 -newer "$SNAP.stamp" 2>/dev/null | sed 's#^\./##' )
} | LC_ALL=C sort -u | while IFS= read -r p; do
  [ -n "$p" ] || continue
  if [ -L "$PREFIX/$p" ]; then
    mkdir -p "$LAYER/$(dirname "$p")"; cp -a "$PREFIX/$p" "$LAYER/$p"
  elif [ -d "$PREFIX/$p" ]; then
    mkdir -p "$LAYER/$p"
  else
    mkdir -p "$LAYER/$(dirname "$p")"; cp -a "$PREFIX/$p" "$LAYER/$p"
  fi
done

# 9. cleanup (next node re-stages the prefix from layer dirs)
rm -rf "$PREFIX" "$BD" "$SNAP.before" "$SNAP.after" "$SNAP.stamp"
|sh}

let install_sh =
  {sh|#!/bin/sh
# Generated by D10ir.Makefile. Minimal opam *.install applier:
# enough of opam-installer to place a package's static <name>.install into
# the staging prefix. Unknown sections are a hard error, never a silent
# skip. Do not edit.
set -eu
BD="$1"; P="$2"; INSTALL="$3"; NAME="$4"

awk '
  function emit(){ if(src!=""){ print sect "|" opt "|" src "|" dst; src="";dst="";opt=0 } }
  { gsub(/\[/," [ "); gsub(/\]/," ] "); gsub(/\{/," { "); gsub(/\}/," } ") }
  {
    n=split($0,a," ");
    for(i=1;i<=n;i++){ t=a[i];
      if(t=="") continue;
      if(t=="["){ inlist=1; continue }
      if(t=="]"){ emit(); inlist=0; sect=""; continue }
      if(t=="{"){ inbrace=1; continue }
      if(t=="}"){ inbrace=0; continue }
      if(!inlist){ s=t; sub(/:$/,"",s); sect=s; continue }
      q=t; sub(/^"/,"",q); sub(/"$/,"",q);
      if(inbrace){ dst=q; continue }
      emit();
      if(substr(q,1,1)=="?"){ opt=1; q=substr(q,2) } else opt=0;
      src=q; dst="";
    }
  }
  END{ emit() }
' "$INSTALL" | while IFS='|' read -r sect opt src dst; do
  [ -n "$src" ] || continue
  base=${dst:-$(basename "$src")}
  case "$sect" in
    bin)          d="$P/bin";          mode=0755 ;;
    sbin)         d="$P/sbin";         mode=0755 ;;
    lib)          d="$P/lib/$NAME";    mode=0644 ;;
    lib_root)     d="$P/lib";          mode=0644 ;;
    libexec)      d="$P/lib/$NAME";    mode=0755 ;;
    libexec_root) d="$P/lib";          mode=0755 ;;
    toplevel)     d="$P/lib/toplevel"; mode=0644 ;;
    stublibs)     d="$P/lib/stublibs"; mode=0755 ;;
    share)        d="$P/share/$NAME";  mode=0644 ;;
    share_root)   d="$P/share";        mode=0644 ;;
    etc)          d="$P/etc/$NAME";    mode=0644 ;;
    doc)          d="$P/doc/$NAME";    mode=0644 ;;
    man)          sec=$(printf '%s' "$base" | sed -n 's/.*\.\([0-9]\).*$/\1/p')
                  d="$P/man/man${sec:-3}"; mode=0644 ;;
    "")           continue ;;
    *) echo "d10-install: unsupported section '$sect' in $NAME.install (build via install: commands instead)" >&2; exit 1 ;;
  esac
  if [ ! -e "$BD/$src" ]; then
    [ "$opt" = 1 ] && continue
    echo "d10-install: missing '$src' for $NAME ($sect)" >&2; exit 1
  fi
  mkdir -p "$d/$(dirname "$base")"
  # Dereference: dune installs META/*.cm* as relative symlinks into its
  # _build tree; -a would preserve them and they would dangle once the
  # build dir is gone. d10ir's Install_file.copy_file follows the link
  # and writes a real file, so the layer is self-contained.
  rm -f "$d/$base"
  cp -L "$BD/$src" "$d/$base"
  chmod "$mode" "$d/$base" 2>/dev/null || true
done
|sh}

(* -- plan walking ------------------------------------------------------- *)

(* The buildable nodes (compiler/toolchain layers dropped — they are
   host-provided), in plan (topological) order, plus hash->node and
   hash->topo-position maps for the transitive walk. *)
type ctx = {
  nodes : Plan.node list;
  by_hash : (string, Plan.node) Hashtbl.t;
  order : (string, int) Hashtbl.t;
}

let is_buildable ctx h = Hashtbl.mem ctx.by_hash h

let build_ctx (plan : Plan.t) =
  let ext = Hashtbl.create 16 in
  List.iter (fun h -> Hashtbl.replace ext (lh h) ()) plan.external_layers;
  let nodes =
    List.filter
      (fun (n : Plan.node) -> not (Hashtbl.mem ext (lh n.layer_hash)))
      plan.nodes
  in
  let by_hash = Hashtbl.create 64 and order = Hashtbl.create 64 in
  List.iteri
    (fun i (n : Plan.node) ->
      Hashtbl.replace by_hash (lh n.layer_hash) n;
      Hashtbl.replace order (lh n.layer_hash) i)
    nodes;
  { nodes; by_hash; order }

(* Fail before writing anything if any buildable node has no pre-baked
   archive — otherwise the generated [fetch] target would 404. *)
let check_archives ctx =
  let missing =
    List.filter_map
      (fun (n : Plan.node) ->
        if n.archive.sha256 = "" then
          Some (n.package.name ^ "." ^ n.package.version)
        else None)
      ctx.nodes
  in
  if missing <> [] then
    failwith
      (Printf.sprintf "d10 makefile: %d package(s) have no source hash: %s."
         (List.length missing)
         (String.concat ", " missing))

(* Transitive closure of a node's buildable deps, deps-first (ascending
   plan position == dependency order, since plan.nodes is topo-sorted). *)
let transitive ctx (n : Plan.node) =
  let seen = Hashtbl.create 32 and acc = ref [] in
  let rec go h =
    if is_buildable ctx h && not (Hashtbl.mem seen h) then (
      Hashtbl.replace seen h ();
      let m : Plan.node = Hashtbl.find ctx.by_hash h in
      List.iter (fun d -> go (lh d)) m.dep_layer_hashes;
      acc := h :: !acc)
  in
  List.iter (fun d -> go (lh d)) n.dep_layer_hashes;
  List.sort_uniq
    (fun a b -> compare (Hashtbl.find ctx.order a) (Hashtbl.find ctx.order b))
    !acc

let direct_dep_stamps ctx (n : Plan.node) =
  n.dep_layer_hashes |> List.map lh
  |> List.filter (is_buildable ctx)
  |> List.sort_uniq compare

(* A non-registry root built from a local source snapshot (the
   no-[TARGET] release flow): same on-disk shape as a node, but its
   tree is pre-shipped under [source/] (sha256="source") and it
   stages the whole dependency closure before building. *)
type local = {
  name : string;
  sha256 : string;
  script : string;
  env : string list;
  prefix : string;
  deps : string list;
}

(* One [recipes/<hash>.*] sidecar set per node (the bulky / quoting-
   hostile fields kept out of the Makefile), plus the two fixed shell
   helpers. *)
let write_sidecars ?local ~config_vars ~output ctx =
  let recipes = output / "recipes" in
  List.iter
    (fun (n : Plan.node) ->
      let h = lh n.layer_hash in
      let nl = String.concat "\n" in
      let bindings = Option.value ~default:[] (List.assoc_opt h config_vars) in
      write
        (recipes / (h ^ ".configvars"))
        (String.concat ""
           (List.map
              (fun (token, file, variable) ->
                token ^ "|" ^ file ^ "|" ^ variable ^ "\n")
              bindings));
      write (recipes / (h ^ ".sh")) n.script;
      write (recipes / (h ^ ".env")) (nl n.env ^ "\n");
      write (recipes / (h ^ ".substs")) (nl n.substs ^ "\n");
      write (recipes / (h ^ ".substvars")) (nl n.subst_vars ^ "\n");
      write (recipes / (h ^ ".prefix")) n.prefix;
      write (recipes / (h ^ ".name")) n.package.name)
    ctx.nodes;
  (match local with
  | None -> ()
  | Some l ->
      let nl = String.concat "\n" in
      write (recipes / (l.name ^ ".configvars")) "";
      write (recipes / (l.name ^ ".sh")) l.script;
      write (recipes / (l.name ^ ".env")) (nl l.env ^ "\n");
      write (recipes / (l.name ^ ".substs")) "\n";
      write (recipes / (l.name ^ ".substvars")) "\n";
      write (recipes / (l.name ^ ".prefix")) l.prefix;
      write (recipes / (l.name ^ ".name")) l.name);
  write ~mode:0o755 (output / "d10-build-node.sh") build_node_sh;
  write ~mode:0o755 (output / "d10-install.sh") install_sh

let overlay_suffix (n : Plan.node) =
  match n.overlay with Some (o : Plan.overlay) -> " @" ^ o.handle | None -> ""

let render_header b ~(plan : Plan.t) ~binaries ~ctx ~tc_name ~roots ~bin_roots
    ~local ~emit_dest_install =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  p "# Generated by D10ir.Makefile — do not edit.\n";
  p "# os_key=%s  toolchain=%s\n" plan.os_key tc_name;
  p
    "# %d buildable node(s); %d compiler/toolchain layer(s) are host-provided.\n"
    (List.length ctx.nodes)
    (List.length plan.external_layers);
  if binaries <> [] then
    p "# binaries: %s\n" (String.concat " " (List.sort_uniq compare binaries));
  p "# Sources are pre-unpacked under sources/<sha>/ — no fetch at make time.\n";
  if emit_dest_install then (
    p "#   make            build all layers, then assemble ./dest (default)\n";
    p "#   make V=1         stream full build output to the terminal\n";
    p "#   make install     copy selected binaries to $(DESTDIR)$(PREFIX)\n";
    p "#   make all         build the layers only (per-node logs in src/log/)\n")
  else (
    p "#   make all         build all layers (per-node logs in src/log/)\n";
    p "#   make V=1         stream full build output to the terminal\n");
  p
    "#   make clean       wipe src/ and dest/ (keeps the shipped sources/ and \
     source/)\n\n";
  p "PREFIX   ?= /usr/local\n";
  p "DESTDIR  ?=\n";
  p "SRC       := src\n";
  p "SHELL     := /bin/sh\n";
  p "V         ?=\n\n";
  p "ROOTS    := %s\n" (String.concat " " roots);
  p "BIN_ROOTS := %s\n\n" (String.concat " " bin_roots);
  (* Default goal: assemble [dest/] for the dist-makefile flow; just
     [all] when the caller will append its own targets (duniverse). *)
  if emit_dest_install then p ".DEFAULT_GOAL := dest\n"
  else p ".DEFAULT_GOAL := all\n";
  (* Shared invariant prefix => nodes must not build concurrently. The
     DAG still orders deps; this only forbids independent branches from
     racing into the one prefix. *)
  p ".NOTPARALLEL:\n";
  if emit_dest_install then p ".PHONY: all check-toolchain clean dest install\n"
  else p ".PHONY: all check-toolchain clean\n";
  let local_stamp =
    match local with
    | Some l -> Fmt.str " $(SRC)/.stamp/layer/%s" l.name
    | None -> ""
  in
  p "all: check-toolchain $(ROOTS:%%=$(SRC)/.stamp/layer/%%)%s\n\n" local_stamp

let render_check_toolchain b ~(plan : Plan.t) ~tc_name =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  p "check-toolchain:\n";
  if plan.external_layers = [] then
    (* Relocatable toolchain: the compiler is in the build graph, so the
       build is fully self-contained — nothing host-provided to check. *)
    p "\t@: # self-contained: compiler '%s' is built from source\n\n" tc_name
  else
    p
      "\t@command -v ocaml >/dev/null 2>&1 || { echo \"d10: OCaml toolchain \
       '%s' must be on PATH (%d compiler layer(s) are host-provided)\" >&2; \
       exit 1; }\n\n"
      tc_name
      (List.length plan.external_layers)

let render_node_rule b ctx (n : Plan.node) =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  let h = lh n.layer_hash in
  let ov = overlay_suffix n in
  let dep_stamps =
    direct_dep_stamps ctx n
    |> List.map (Printf.sprintf "$(SRC)/.stamp/layer/%s")
    |> String.concat " "
  in
  let trans = transitive ctx n in
  p "# %s.%s%s\n" n.package.name n.package.version ov;
  p "$(SRC)/.stamp/layer/%s:%s%s\n" h
    (if dep_stamps = "" then "" else " ")
    dep_stamps;
  p "\t@mkdir -p $(SRC)/.stamp/layer\n";
  p "\t@echo \"  BUILD  %s.%s%s\"\n" n.package.name n.package.version ov;
  p "\t@V='$(V)' DIST='$(SRC)' $(SHELL) ./d10-build-node.sh %s %s%s%s\n" h
    n.archive.sha256
    (if trans = [] then "" else " ")
    (String.concat " " trans);
  p "\t@touch $@\n\n"

(* The local-source root: stages the whole dep closure into the prefix
   before running the project build. Its tree is shipped under
   [source/], so the build script's $ROOT/<sha>/ branch with
   sha="source" picks it up — no fetch, no decompress. *)
let render_local_rule b ctx (l : local) =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  let all_hashes =
    List.map (fun (n : Plan.node) -> lh n.layer_hash) ctx.nodes
  in
  let dep_stamps =
    all_hashes
    |> List.map (Printf.sprintf "$(SRC)/.stamp/layer/%s")
    |> String.concat " "
  in
  p "# %s (local source snapshot)\n" l.name;
  p "$(SRC)/.stamp/layer/%s:%s%s\n" l.name
    (if dep_stamps = "" then "" else " ")
    dep_stamps;
  p "\t@mkdir -p $(SRC)/.stamp/layer\n";
  p "\t@echo \"  BUILD  %s (local)\"\n" l.name;
  p "\t@V='$(V)' DIST='$(SRC)' $(SHELL) ./d10-build-node.sh %s %s%s%s\n" l.name
    l.sha256
    (if all_hashes = [] then "" else " ")
    (String.concat " " all_hashes);
  p "\t@touch $@\n\n"

let render_clean b =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  (* Keep [source/] (the shipped project snapshot — a persistent input,
     not a re-fetchable artefact) and the generated Makefile/recipes. *)
  p "clean:\n\t@rm -rf $(SRC) dest\n\n"

(* [dest]/[install] take only the selected package(s)' own bin/sbin
   (+ share for install) — never the dependency closure. *)
let render_dest_install b =
  let p fmt = Printf.ksprintf (fun s -> Buffer.add_string b s) fmt in
  p "dest: all\n";
  p "\t@rm -rf dest\n";
  p
    "\t@for h in $(BIN_ROOTS); do for d in bin sbin; do if [ -d \
     \"$(SRC)/layers/$$h/$$d\" ]; then mkdir -p \"dest/$$d\"; cp -a \
     \"$(SRC)/layers/$$h/$$d/.\" \"dest/$$d/\"; fi; done; done\n";
  p "\t@echo \"dest/ — selected package binaries:\"\n";
  p
    "\t@{ ls dest/bin 2>/dev/null | sed 's|^|  dest/bin/|'; ls dest/sbin \
     2>/dev/null | sed 's|^|  dest/sbin/|'; } || true\n\n";
  p "install: all\n";
  p
    "\t@for h in $(BIN_ROOTS); do for d in bin sbin share; do if [ -d \
     \"$(SRC)/layers/$$h/$$d\" ]; then mkdir -p \"$(DESTDIR)$(PREFIX)/$$d\"; \
     cp -a \"$(SRC)/layers/$$h/$$d/.\" \"$(DESTDIR)$(PREFIX)/$$d/\"; fi; done; \
     done\n";
  p "\t@echo \"installed selected package(s) to $(DESTDIR)$(PREFIX)\"\n"

let emit (plan : Plan.t) ~output ?(binaries = []) ?(bin_roots = [])
    ?(emit_dest_install = true) ?local ?(config_vars = []) () =
  let ctx = build_ctx plan in
  check_archives ctx;
  write_sidecars ?local ~config_vars ~output ctx;
  (* The full merged d10ir plan, for debugging: every node's package,
     layer hash, dep_layer_hashes and resolved script/env. Inspecting
     this is how you tell whether e.g. an opam [depopt] actually became
     a dependency edge (jsont -> bytesrw). Not consumed by [make]. *)
  write (output / "plan.json") (Plan.to_string plan);
  let roots =
    plan.roots |> List.map lh
    |> List.filter (is_buildable ctx)
    |> List.sort_uniq compare
  in
  (* [dest]/[install] target the local snapshot when present, else the
     request roots, falling back to the plan roots so they are never
     empty by accident. *)
  let bin_roots =
    match local with
    | Some l -> [ l.name ]
    | None ->
        let f =
          List.filter (is_buildable ctx) bin_roots |> List.sort_uniq compare
        in
        if f <> [] then f else roots
  in
  let tc_name = (plan.toolchain : Plan.toolchain).name in
  let b = Buffer.create 8192 in
  render_header b ~plan ~binaries ~ctx ~tc_name ~roots ~bin_roots ~local
    ~emit_dest_install;
  render_check_toolchain b ~plan ~tc_name;
  List.iter (fun n -> render_node_rule b ctx n) ctx.nodes;
  (match local with Some l -> render_local_rule b ctx l | None -> ());
  render_clean b;
  if emit_dest_install then render_dest_install b;
  write (output / "Makefile") (Buffer.contents b)
