(test
 (name test)
 (package console)
 (modules
  test
  test_anim
  test_bar
  test_border
  test_guide
  test_color
  test_gradient
  test_canvas
  test_panel
  test_spinner
  test_theme
  test_span
  test_style
  test_console
  test_tree
  test_rule
  test_layout
  test_width
  test_input)
 (libraries console alcotest re fmt logs))
