(mdx
 (package fetch)
 (deps
  (package mtime)
  (package duration)
  (package bytesrw)
  (package base64)
  (package cmarkit)
  (package cstruct)
  (package domain-name)
  (package eio)
  (package eio_linux)
  (package eio_main)
  (package eio_posix)
  (package fetch)
  (package hmap)
  (package httpz)
  (package uriz)
  (package ipaddr)
  (package macaddr)
  (package jsont)
  (package lwt-dllist)
  (package optint)
  (package ptime)
  (package uring)))

(test
 (name test_sse)
 (package fetch)
 (libraries duration fetch fetch.mock eio.mock cstruct eio http))

(test
 (name test_redirect)
 (package fetch)
 (libraries fetch fetch.mock eio.mock eio http httpz.uri))

(test
 (name test_idle_timeout)
 (package fetch)
 (libraries duration fetch eio.mock alcotest cstruct eio))

(test
 (name test_release)
 (package fetch)
 (libraries duration fetch fetch.mock eio.mock http eio mtime))

(test
 (name test_url_policy)
 (package fetch)
 (libraries fetch fetch.mock eio.mock httpz.uri eio))

(test
 (name test_cookies_store_error)
 (package fetch)
 (libraries fetch fetch.cookies fetch.mock alcotest eio_main eio http))

(test
 (name test_form_boundary)
 (package fetch)
 (libraries fetch alcotest httpz.media))
