(*---------------------------------------------------------------------------
  Copyright (c) 2025 Anil Madhavapeddy <anil@recoil.org>. All rights reserved.
  SPDX-License-Identifier: ISC
 ---------------------------------------------------------------------------*)

(** Sortal configuration management with XDG paths *)

(** {1 Types} *)

type t = {
  (* Git sync *)
  sync : Gitops.Sync.Config.t;
  carddav : carddav;
}

and carddav = {
  server : string;
  username : string;
  password_file : string;
  collection : string option;
  bundle : string;
  report : string;
}

(** {1 XDG Paths} *)

let xdg_config_home () =
  match Sys.getenv_opt "XDG_CONFIG_HOME" with
  | Some dir -> dir
  | None -> (
      match Sys.getenv_opt "HOME" with
      | Some home -> Filename.concat home ".config"
      | None -> ".config")

let xdg_data_home () =
  match Sys.getenv_opt "XDG_DATA_HOME" with
  | Some dir -> dir
  | None -> (
      match Sys.getenv_opt "HOME" with
      | Some home -> Filename.concat home ".local/share"
      | None -> ".local/share")

let config_dir () = Filename.concat (xdg_config_home ()) "sortal"
let config_file () = Filename.concat (config_dir ()) "config.toml"
let data_dir () = Filename.concat (xdg_data_home ()) "sortal"

let state_dir () =
  match Sys.getenv_opt "XDG_STATE_HOME" with
  | Some dir -> dir
  | None -> (
      match Sys.getenv_opt "HOME" with
      | Some home -> Filename.concat home ".local/state"
      | None -> ".local/state")

(** {1 Default Configuration} *)

let default () =
  {
    sync = Gitops.Sync.Config.default;
    carddav =
      {
        server = "https://carddav.fastmail.com/";
        username = "";
        password_file = Filename.concat (config_dir ()) "carddav-password";
        collection = None;
        bundle = Filename.concat (state_dir ()) "sortal/carddav/bundle";
        report = Filename.concat (state_dir ()) "sortal/carddav/report";
      };
  }

(** {1 Tomlt Codecs} *)

let config_codec =
  let open Tomlt.Table in
  obj (fun sync carddav -> { sync; carddav })
  |> mem "sync" Gitops.Sync.Config.codec ~dec_absent:Gitops.Sync.Config.default
       ~enc:(fun c -> c.sync)
  |> mem "carddav"
       (let open Tomlt.Table in
        obj (fun server username password_file collection bundle report ->
            {
              server;
              username;
              password_file;
              collection = (if collection = "" then None else Some collection);
              bundle;
              report;
            })
        |> mem "server" Tomlt.string ~dec_absent:(default ()).carddav.server
             ~enc:(fun d -> d.server)
        |> mem "username" Tomlt.string ~dec_absent:"" ~enc:(fun d -> d.username)
        |> mem "password_file" Tomlt.string
             ~dec_absent:(default ()).carddav.password_file ~enc:(fun d ->
               d.password_file)
        |> mem "collection" Tomlt.string ~dec_absent:"" ~enc:(fun d ->
            Option.value ~default:"" d.collection)
        |> mem "bundle" Tomlt.string ~dec_absent:(default ()).carddav.bundle
             ~enc:(fun d -> d.bundle)
        |> mem "report" Tomlt.string ~dec_absent:(default ()).carddav.report
             ~enc:(fun d -> d.report)
        |> finish)
       ~dec_absent:(default ()).carddav
       ~enc:(fun c -> c.carddav)
  |> finish

(** {1 Loading} *)

let of_string s =
  match Tomlt_bytesrw.decode_string config_codec s with
  | Ok config -> Ok config
  | Error e -> Error (Tomlt.Toml.Error.to_string e)

let load_file path =
  try
    let ic = open_in path in
    let content = really_input_string ic (in_channel_length ic) in
    close_in ic;
    of_string content
  with Sys_error msg -> Error (Printf.sprintf "Failed to read config: %s" msg)

let load () =
  let path = config_file () in
  if Sys.file_exists path then load_file path else Ok (default ())

(** {1 Pretty Printing} *)

let pp ppf t =
  let open Fmt in
  pf ppf "@[<v>";
  pf ppf "%a:@," (styled `Bold string) "Sortal Configuration";
  pf ppf "  data_dir: %s@," (data_dir ());
  pf ppf "  sync remote: %s@," t.sync.Gitops.Sync.Config.remote;
  pf ppf "  carddav server: %s@," t.carddav.server;
  pf ppf "  carddav user: %s@," t.carddav.username;
  pf ppf "@]"

(** {1 Default Config Generation} *)

let default_config_toml () =
  Printf.sprintf
    {|# Sortal Configuration
# Generated by: sortal init

# Git sync configuration
# Sync your sortal data to a remote git repository
[sync]
remote = ""
branch = "main"
auto_commit = true
commit_message = "sync"

# CardDAV synchronization. The password file is created beside this config
# with mode 0600 by `sortal init`.
[carddav]
server = "https://carddav.fastmail.com/"
username = ""
password_file = %S
collection = ""
bundle = %S
report = %S
|}
    (Filename.concat (config_dir ()) "carddav-password")
    (Filename.concat (state_dir ()) "sortal/carddav/bundle")
    (Filename.concat (state_dir ()) "sortal/carddav/report")

let write_default_config ?(force = false) () =
  let dir = config_dir () in
  let path = config_file () in

  (* Check if config already exists *)
  if Sys.file_exists path && not force then
    Error
      (Printf.sprintf
         "Config file already exists: %s\nUse --force to overwrite." path)
  else begin
    (* Create directory if needed *)
    if not (Sys.file_exists dir) then begin
      Unix.mkdir dir 0o755
    end;

    (* Write config file *)
    let content = default_config_toml () in
    let oc = open_out path in
    output_string oc content;
    close_out oc;
    let password = Filename.concat dir "carddav-password" in
    (if not (Sys.file_exists password) then
       let fd =
         Unix.openfile password
           [ Unix.O_CREAT; Unix.O_EXCL; Unix.O_WRONLY ]
           0o600
       in
       Unix.close fd);
    Ok path
  end
