module DF = Dockerfile

let ( @@ ) = Dockerfile.( @@ )

let tarball_filename (s : Spec.t) (t : Target.t) =
  Fmt.str "%s-%s-linux-%s-static.tar.gz" s.package s.version t.arch

(* Single-stage: install the apk toolchain + overlay depexts and stage
   the source tarball at image-build time; the actual compile and
   install run at container-run time so [docker compose up --build]
   with [/artefacts] bind-mounted to ./artefacts/<tag>/ tars the
   binaries straight into the host. *)
let dockerfile ?(overlay_depexts = []) (s : Spec.t) (t : Target.t) =
  let base_apk_pkgs =
    "build-base m4 perl pkgconf git curl bash patch gmp-dev sqlite-dev \
     sqlite-static openssl-dev openssl-libs-static zlib-dev zlib-static"
  in
  let base_words =
    String.split_on_char ' ' base_apk_pkgs |> List.filter (fun s -> s <> "")
  in
  (* Overlay depexts come from the bundle sidecar, evaluated against
     [os-distribution = "alpine"]. Dedup against the bootstrap toolchain
     so packages like [git] / [linux-headers] never appear twice on the
     apk add line. *)
  let overlay_extras =
    overlay_depexts
    |> List.filter (fun p -> not (List.mem p base_words))
    |> List.sort_uniq String.compare
  in
  let apk_build_pkgs =
    match overlay_extras with
    | [] -> base_apk_pkgs
    | xs -> base_apk_pkgs ^ " " ^ String.concat " " xs
  in
  let tarball = tarball_filename s t in
  let runtime_cmd =
    Fmt.str
      "set -eu; cd /home/opam/src/%s-%s; ./build.sh build $(nproc); ./build.sh \
       install /usr /dist; tar --transform 's,^./,%s-%s-linux-%s-static/,' \
       -czf /artefacts/%s -C /dist/usr/bin .; cd /artefacts && sha256sum %s > \
       %s.sha256"
      s.package s.version s.package s.version t.arch tarball tarball tarball
  in
  DF.comment "Generated by `oi dist pkg` — static musl build of %s on alpine."
    s.package
  @@ DF.parser_directive (`Syntax "docker/dockerfile:1.6")
  @@ DF.from t.base_image @@ DF.user "root"
  @@ DF.run "apk add --no-cache %s" apk_build_pkgs
  (* /dist (DESTDIR for build.sh install) and /artefacts (host volume
     mount) both have to be writable by the [opam] user that runs the
     build. [chmod 0777 /artefacts] also lets the runtime [tar] from
     [opam] succeed regardless of the host bind-mount owner. *)
  @@ DF.run
       "mkdir -p /dist /artefacts && chown opam:opam /dist && chmod 0777 \
        /artefacts"
  @@ DF.user "opam"
  @@ DF.workdir "/home/opam/src"
  @@ DF.copy ~chown:"opam:opam"
       ~src:[ Fmt.str "%s-%s.tar.gz" s.package s.version ]
       ~dst:"/home/opam/src/" ()
  @@ DF.env [ ("OI_STATIC", "1"); ("CI", "true") ]
  (* Source extraction is deterministic given the bundle hash: do it at
     image-build time so the [up] phase only has the compile to run. *)
  @@ DF.run "tar -xzf %s-%s.tar.gz" s.package s.version
  @@ DF.cmd_exec [ "sh"; "-c"; runtime_cmd ]

let build_sh (s : Spec.t) (t : Target.t) =
  let tarball = tarball_filename s t in
  Fmt.str
    {|#!/bin/sh
# Generated by `oi dist pkg`. Builds the static-musl Dockerfile and runs
# the resulting image with /artefacts bind-mounted into this dir so the
# image's CMD writes %s + the sha256 sidecar straight into $HERE.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
# 0777 so the container's [opam] user (UID 1000) can write regardless
# of the host owner.
chmod 0777 "$HERE" || true
IMG="osdist-build-%s-%s:latest"
docker build -t "$IMG" "$HERE"
docker run --rm -v "$HERE:/artefacts" "$IMG"
echo "wrote $HERE/%s"
|}
    tarball s.package t.arch tarball
