type config = {
  baseurl : string;
  origin : string;
  label : string;
  description : string;
  gpg_key_id : string;
  pubkey_filename : string;
}

(* Unique sorted codenames from a target list (deb targets only — rpm /
   static have [codename = None]). *)
let unique_codenames targets =
  List.filter_map (fun (t : Target.t) -> t.codename) targets
  |> List.sort_uniq String.compare

let apt_distributions cfg ~deb_targets =
  unique_codenames deb_targets
  |> List.map (fun cn ->
      Fmt.str
        "Origin: %s\n\
         Label: %s\n\
         Codename: %s\n\
         Components: main\n\
         Architectures: amd64\n\
         Description: %s (%s)\n\
         SignWith: %s\n"
        cfg.origin cfg.label cn cfg.description cn cfg.gpg_key_id)
  |> String.concat "\n"

let dnf_repo_file cfg (t : Target.t) ~pkg =
  Fmt.str
    "[%s]\n\
     name=%s %s\n\
     baseurl=%s/rpm/%s\n\
     enabled=1\n\
     gpgcheck=1\n\
     repo_gpgcheck=1\n\
     gpgkey=%s/rpm/%s/%s\n"
    pkg cfg.origin t.tag cfg.baseurl t.tag cfg.baseurl t.tag cfg.pubkey_filename

(* -- install.sh ---------------------------------------------------------
   Lightweight POSIX-sh installer; same shape as the oxcaml-pkgs one.
   {{}} are deliberate quoting markers; the template uses single-quoted
   heredocs so OCaml-side escaping stays sane. *)
let install_sh cfg (s : Spec.t) ~targets =
  let deb_targets =
    List.filter (fun (t : Target.t) -> t.family = Target.Deb) targets
  in
  let rpm_targets =
    List.filter (fun (t : Target.t) -> t.family = Target.Rpm) targets
  in
  let has_static =
    List.exists (fun (t : Target.t) -> t.family = Target.Static) targets
  in
  let codenames = unique_codenames deb_targets |> String.concat " " in
  let rpm_tags =
    List.map (fun (t : Target.t) -> t.tag) rpm_targets |> String.concat " "
  in
  Fmt.str
    {|#!/bin/sh
# %s installer — generated by `oi dist repo` from osdist.
#
#   curl -fsSL %s/install.sh | sh
#   curl -fsSL %s/install.sh | sh -s -- --static
#
set -eu
DEFAULT_REPO_URL="%s"
PKG="%s"
DEB_CODENAMES="%s"
RPM_TAGS="%s"
PUBKEY="%s"
REPO_URL="${%s_REPO_URL:-$DEFAULT_REPO_URL}"
FORCE_STATIC=0
PREFIX=""
while [ $# -gt 0 ]; do
  case "$1" in
    --repo-url) REPO_URL="${2:?--repo-url needs an argument}"; shift 2 ;;
    --repo-url=*) REPO_URL="${1#*=}"; shift ;;
    --static) FORCE_STATIC=1; shift ;;
    --prefix) PREFIX="${2:?--prefix needs an argument}"; shift 2 ;;
    --prefix=*) PREFIX="${1#*=}"; shift ;;
    -h|--help)
      printf '%%s\n' "Usage: install.sh [--repo-url URL] [--static] [--prefix DIR]"
      exit 0 ;;
    *) echo "install.sh: unknown argument '$1'" >&2; exit 2 ;;
  esac
done
REPO_URL="${REPO_URL%%/}"
say()  { printf '==> %%s\n' "$*"; }
die()  { printf 'ERROR: %%s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
SUDO=""
if [ "$(id -u)" -ne 0 ] && have sudo; then SUDO="sudo"; fi
fetch() {
  if have curl; then curl -fsSL "$1"
  elif have wget; then wget -qO- "$1"
  else die "need curl or wget"
  fi
}
ID=""; VERSION_CODENAME=""
[ -r /etc/os-release ] && . /etc/os-release
codename_supported() {
  for c in $DEB_CODENAMES; do [ "$c" = "$1" ] && return 0; done; return 1
}
rpm_tag_for() {
  case "$1:$2" in
    fedora:44) echo fedora-44 ;;
    fedora:43) echo fedora-43 ;;
    *) echo "" ;;
  esac
}
install_deb() {
  codename_supported "$VERSION_CODENAME" || return 1
  $SUDO mkdir -p /usr/share/keyrings /etc/apt/sources.list.d
  fetch "$REPO_URL/apt/$PUBKEY" | $SUDO gpg --dearmor -o "/usr/share/keyrings/${PKG}.gpg"
  echo "deb [signed-by=/usr/share/keyrings/${PKG}.gpg] $REPO_URL/apt $VERSION_CODENAME main" \
    | $SUDO tee "/etc/apt/sources.list.d/${PKG}.list" >/dev/null
  $SUDO apt-get update
  $SUDO apt-get install -y "$PKG"
}
install_rpm() {
  tag=$(rpm_tag_for "$ID" "$VERSION_ID")
  [ -n "$tag" ] || return 1
  case " $RPM_TAGS " in *" $tag "*) : ;; *) return 1 ;; esac
  $SUDO rpm --import "$REPO_URL/rpm/$tag/$PUBKEY"
  $SUDO tee "/etc/yum.repos.d/${PKG}.repo" >/dev/null <<EOF
[${PKG}]
name=${PKG} ($tag)
baseurl=$REPO_URL/rpm/$tag
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=$REPO_URL/rpm/$tag/$PUBKEY
EOF
  $SUDO dnf install -y "$PKG"
}
install_static() {
  arch=$(uname -m)
  url="$REPO_URL/bin/${PKG}-latest-linux-${arch}-static.tar.gz"
  say "downloading $url"
  tmp=$(mktemp -d)
  fetch "$url" > "$tmp/bin.tgz"
  tar -xzf "$tmp/bin.tgz" -C "$tmp" --strip-components=1
  dst="${PREFIX:-$HOME/.local}/bin"
  mkdir -p "$dst"
  for f in "$tmp"/*; do install -m0755 "$f" "$dst/$(basename "$f")"; done
  rm -rf "$tmp"
  say "installed to $dst"
}
if [ "$FORCE_STATIC" -eq 1 ]; then install_static; exit 0; fi
case "${ID}" in
  ubuntu|debian) install_deb && exit 0 ;;
  fedora) install_rpm && exit 0 ;;
esac
%s
say "no native package for $ID; falling back to static binary"
install_static
|}
    s.package cfg.baseurl cfg.baseurl cfg.baseurl s.package codenames rpm_tags
    cfg.pubkey_filename
    (String.uppercase_ascii s.package)
    (if has_static then ""
     else "die 'no static fallback configured; use --repo-url or pass --static'")

let install_md cfg (s : Spec.t) ~targets =
  let deb_targets =
    List.filter (fun (t : Target.t) -> t.family = Target.Deb) targets
  in
  let rpm_targets =
    List.filter (fun (t : Target.t) -> t.family = Target.Rpm) targets
  in
  let static_targets =
    List.filter (fun (t : Target.t) -> t.family = Target.Static) targets
  in
  let buf = Buffer.create 4096 in
  let ppf = Fmt.with_buffer buf in
  Fmt.pf ppf
    "# Installing %s@.@.## Quick install@.@.```sh@.curl -fsSL %s/install.sh | \
     sh@.```@.@."
    s.package cfg.baseurl;
  if deb_targets <> [] then begin
    Fmt.pf ppf "## Debian / Ubuntu@.@.```sh@.";
    Fmt.pf ppf
      "curl -fsSL %s/apt/%s | sudo gpg --dearmor -o \
       /usr/share/keyrings/%s.gpg@."
      cfg.baseurl cfg.pubkey_filename s.package;
    Fmt.pf ppf "# pick the line for your release:@.";
    List.iter
      (fun cn ->
        Fmt.pf ppf
          "echo 'deb [signed-by=/usr/share/keyrings/%s.gpg] %s/apt %s main' | \
           sudo tee /etc/apt/sources.list.d/%s.list@."
          s.package cfg.baseurl cn s.package)
      (unique_codenames deb_targets);
    Fmt.pf ppf "sudo apt update && sudo apt install %s@.```@.@." s.package
  end;
  if rpm_targets <> [] then begin
    Fmt.pf ppf "## Fedora@.@.";
    List.iter
      (fun (t : Target.t) ->
        Fmt.pf ppf "`/etc/yum.repos.d/%s.repo` (%s):@.@.```sh@." s.package t.tag;
        Fmt.pf ppf
          "sudo rpm --import %s/rpm/%s/%s@.sudo tee /etc/yum.repos.d/%s.repo \
           >/dev/null <<'EOF'@."
          cfg.baseurl t.tag cfg.pubkey_filename s.package;
        Buffer.add_string buf (dnf_repo_file cfg t ~pkg:s.package);
        Fmt.pf ppf "EOF@.sudo dnf install %s@.```@.@." s.package)
      rpm_targets
  end;
  if static_targets <> [] then
    Fmt.pf ppf
      "## Static binary (any glibc/musl Linux)@.@.```sh@.curl -fsSL \
       %s/install.sh | sh -s -- --static@.```@.@.Or directly:@.@.```sh@.curl \
       -fsSL %s/bin/%s-latest-linux-$(uname -m)-static.tar.gz \\@.  | tar -xz \
       -C ~/.local --strip-components=1@.```@.@."
      cfg.baseurl cfg.baseurl s.package;
  Fmt.pf ppf "Signed with GPG key %s.@." cfg.gpg_key_id;
  Buffer.contents buf
