(test
 (name test_proto_uri)
 (modules test_proto_uri)
 (libraries apubt.proto jsont.bytesrw uriz))

(test
 (name test_client)
 (modules test_client)
 (libraries apubt fetch.mock eio.mock http uri jsont.bytesrw
  mirage-crypto-pk mirage-crypto-rng.unix))

(test
 (name test_auth)
 (modules test_auth)
 (libraries apubt.auth fetch.mock eio.mock http uri))

(test
 (name test_review)
 (modules test_review)
 (libraries apubt fetch.mock eio.mock http jsont.bytesrw))

(test
 (name test_session)
 (modules test_session)
 (libraries apubt.auth eio_main unix jsont.bytesrw))
