(rule
 (alias runtest)
 (deps integration.py)
 (action
  (run python3 %{dep:integration.py} %{exe:../bin/main.exe})))

(rule
 (alias runtest)
 (deps day10.py)
 (action
  (run python3 %{dep:day10.py} %{exe:../bin/main.exe})))

(rule
 (alias runtest)
 (deps dist.py)
 (action
  (run python3 %{dep:dist.py} %{exe:../bin/main.exe})))

(rule
 (alias runtest)
 (deps workflows.py)
 (action
  (run python3 %{dep:workflows.py} %{exe:../bin/main.exe})))
