(lang dune 3.20)
(name osrel)
(version 0.14.2)
(generate_opam_files true)
(license ISC)
(maintainers "Anil Madhavapeddy <anil@recoil.org>")
(authors "Anil Madhavapeddy" "Mark Elvers" "Ryan Gibb")
(source (github avsm/oi))

(package
 (name osrel)
 (synopsis "OS and platform detection via Eio")
 (depends
  (ocaml (>= 5.2.0))
  (eio (>= 1.0))
  fmt
  (alcotest :with-test)
  (eio_main :with-test)))
