; The first rule asserts the current behaviour; the second shows the
; workaround used by the vendored Eio (Peff module).

(rule
 (alias runtest)
 (action
  (with-accepted-exit-codes 2
   (run %{bin:ocamlopt} -color never -c %{dep:repro.ml}))))

(rule
 (alias runtest)
 (action (run %{bin:ocamlopt} -color never -c %{dep:workaround.ml})))
