(lang dune 3.21)
(name termanil)
(generate_opam_files true)
(cram enable)
(license ISC)
(authors "Anil Madhavapeddy")
(maintainers "Anil Madhavapeddy <anil@recoil.org>")
(package
 (name termanil)
 (synopsis "Bonsai terminal workspace for JMAP mail, Sortal contacts and Dooit")
 (depends
  (ocaml (>= 5.2.0))
  bonsai_term bonsai_term_components bonsai core async ppx_jane sexplib ppx_sexp_conv
  eio eio_main cmdliner xdge tomlt dooit sortal jmap
  fetch fetch-curl jsont ptime markup uutf uunf uucp duration
  (bonsai_term_test :with-test)
  (bonsai_test :with-test)))
