when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - shell
    - stdenv
    - findutils
    - binutils
    - libunwind
    - ncurses
    - opam
    - git
    - gawk
    - gnupatch
    - gnum4
    - gnumake
    - gnutar
    - gnused
    - gnugrep
    - diffutils
    - gzip
    - bzip2
    - gcc
    - ocaml
    - pkg-config

steps:
  - name: opam
    command: |
       opam init --disable-sandboxing -a -y
  - name: repo
    command: |
       opam repo add aoah https://tangled.org/anil.recoil.org/aoah-opam-repo.git
  - name: switch
    command: |
       opam install . --confirm-level=unsafe-yes --deps-only
  - name: build
    command: |
       opam exec -- dune build yamlrw.install yamlrw-unix.install yamlrw-eio.install
  - name: switch-test
    command: |
       opam install . --confirm-level=unsafe-yes --deps-only --with-test
  - name: test
    command: |
       opam exec -- dune runtest --verbose
  - name: doc
    command: |
       opam install -y odoc
       opam exec -- dune build @doc
  - name: yaml-test-suite-setup
    command: |
       git clone --depth 1 -b data https://github.com/yaml/yaml-test-suite tests/yaml-test-suite
  - name: yaml-test-suite
    command: |
       opam exec -- dune build @yaml-test-suite
       opam exec -- dune build @yaml-test-suite-eio
