(lang dune 3.21)
(using mdx 0.4)

(name json-pointer)

(generate_opam_files true)

(license ISC)
(authors "Anil Madhavapeddy")
(maintainers "Anil Madhavapeddy <anil@recoil.org>")
(source (tangled anil.recoil.org/ocaml-json-pointer))

(package
 (name json-pointer)
 (synopsis "RFC 6901 JSON Pointer implementation for jsont")
 (description
  "This library provides RFC 6901 JSON Pointer parsing, serialization, \
   and evaluation for jsont values and codecs. It also provides the RFC 6902 \
   JSON Patch operations and RFC 8620 JMAP wildcard evaluation.")
 (depends
  (ocaml (>= 5.2.0))
  (jsont (>= 0.3.0))
  uriz
  (bytesrw (and (>= 0.3.0) :with-test))
  (mdx (and (>= 2.4.1) :with-test))
  (odoc :with-doc)))
