#!/usr/bin/env python3
"""Embed the complete vendored lexicon catalogue for offline CLI discovery."""
import json
from pathlib import Path
import sys

root = Path(sys.argv[1])
print('(* Generated by tools/tangled_endpoints.py. *)')
print('let documents = [')
for path in sorted(root.rglob('*.json')):
    doc = json.loads(path.read_text())
    print('  %s, %s;' % (json.dumps(doc['id']),
          json.dumps(json.dumps(doc, separators=(',', ':')))))
print(']')
