(lang dune 3.21)

(name jsonwt)

(generate_opam_files true)

(license ISC)

(authors "Anil Madhavapeddy")

(maintainers "anil@recoil.org")

(source
 (tangled anil.recoil.org/ocaml-jsonwt))

(package
 (name jsonwt)
 (synopsis "Bounded JSON Web Tokens for OxCaml")
 (depends
  (ocaml
   (>= 5.2))
  jsont
  bytesrw
  digestif
  eqaf
  base64
  ptime
  uriz
  mirage-crypto-ec
  mirage-crypto-rng
  conf-libssl
  cbort
  zarith
  (cstruct :with-test)
  (crowbar :with-test)
  (alcotest :with-test)))
