(test
 (name test_server)
 (modules test_server)
 (libraries proffer.dav proffer proffer.mock httpz httpz.dav))

(executable
 (name fixture)
 (modules fixture)
 (libraries
  proffer.dav
  proffer.dav.eio
  proffer
  proffer-httpz
  duration
  eio
  eio_main
  digestif
  base64
  x509
  tls
  httpz.tls))
