(test
 (name test_dagcbor_atproto)
 (modules test_dagcbor_atproto)
 (libraries atp))

(test
 (name test_syntax)
 (modules test_syntax)
 (libraries atp)
 (deps
  (glob_files fixtures/syntax/*.txt)))

(test
 (name test_review)
 (modules test_review)
 (libraries atp bytesrw))

(test
 (name test_dagcbor_large)
 (modules test_dagcbor_large)
 (libraries atp bytesrw))

(test
 (name test_dagcbor_prefix)
 (modules test_dagcbor_prefix)
 (libraries atp bytesrw))
