(rule
 (target normalized.json)
 (deps ../normalize.py ../openapi.json)
 (action
  (with-stdout-to
   %{target}
   (run python3 %{dep:../normalize.py} %{dep:../openapi.json}))))

(rule
 (targets openrouter_api.ml openrouter_api.mli)
 (deps normalized.json)
 (action
  (run
   %{bin:openapi-gen}
   generate
   --code-only
   --fetch-only
   -o
   .
   -n
   openrouter_api
   %{deps})))

(library
 (name openrouter_api)
 (package openrouter)
 (libraries openapi jsont jsont.bytesrw fetch ptime eio))
