(mdx
 (package fetch-curl)
 (deps
  (package bytesrw)
  (package checkseum)
  (package base64)
  (package cmarkit)
  (package cstruct)
  (package decompress)
  (package domain-name)
  (package eio)
  (package eio_linux)
  (package eio_main)
  (package eio_posix)
  (package fetch-curl)
  (package fetch)
  (package hmap)
  (package httpz)
  (package uriz)
  (package ipaddr)
  (package jsont)
  (package lwt-dllist)
  (package macaddr)
  (package optint)
  (package ptime)
  (package uring)))

(test
 (name test_transport)
 (package fetch-curl)
 (deps h2_fixture.py)
 (libraries fetch fetch-curl httpz httpz.tls alcotest cstruct eio eio_main fmt
  ptime tls x509 mirage-crypto-rng.unix))
