Port 22
HostKey /etc/ssh/ssh_host_ed25519_key
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
UsePAM no
AllowUsers git
AuthorizedKeysFile none
AuthorizedKeysCommand /usr/local/bin/knot-keys
AuthorizedKeysCommandUser nobody
DisableForwarding yes
