(* Generated by gen_vectors.py, do not edit.  Regenerate with

     /home/avsm2/src/git/avsm/geotessera/.venv/bin/python \
       bleeding/tessera/test/geodesy/gen_vectors.py \
       > bleeding/tessera/test/geodesy/crs_vectors.ml

   from the repository root, using pyproj 3.7.2.  [e] and [n] are
   where [(lon, lat)] lands, and [ilon] and [ilat] are where
   [(e, n)] comes back to. *)

type utm = {
  zone : int;
  lon : float;
  lat : float;
  e : float;
  n : float;
  ilon : float;
  ilat : float;
}

type patch = {
  p_lon : float;
  p_lat : float;
  p_crs : string;
  p_lon_in : float;
  p_lat_in : float;
  p_e : float;
  p_n : float;
  p_ilon : float;
  p_ilat : float;
}

let utm =
  [
    { zone = 1; lon = -177.0; lat = 52.0;
      e = 500000.0; n = 5761038.212590415;
      ilon = -177.0; ilat = 52.0 };
    { zone = 1; lon = -177.0; lat = -55.0;
      e = 500000.0; n = -6094791.420998934;
      ilon = -177.0; ilat = -54.99999999999999 };
    { zone = 1; lon = -175.0; lat = 52.0;
      e = 637294.3658943711; n = 5762926.812914039;
      ilon = -175.0; ilat = 52.0 };
    { zone = 1; lon = -175.0; lat = -55.0;
      e = 627928.1913765114; n = -6096620.706492609;
      ilon = -175.0; ilat = -55.0 };
    { zone = 30; lon = -3.0; lat = 52.0;
      e = 499999.9999999994; n = 5761038.212590415;
      ilon = -3.0; ilat = 52.0 };
    { zone = 30; lon = -3.0; lat = 0.0;
      e = 499999.999999999; n = 0.0;
      ilon = -3.0000000000000004; ilat = 0.0 };
    { zone = 30; lon = -1.0; lat = 52.0;
      e = 637294.3658943702; n = 5762926.812914039;
      ilon = -1.0000000000000007; ilat = 52.0 };
    { zone = 30; lon = -1.0; lat = 0.0;
      e = 722595.4396756799; n = 0.0;
      ilon = -1.0000000000000002; ilat = 0.0 };
    { zone = 31; lon = 3.0; lat = 52.0;
      e = 500000.0000000006; n = 5761038.212590415;
      ilon = 3.0; ilat = 52.0 };
    { zone = 31; lon = 3.0; lat = -30.0;
      e = 500000.0000000008; n = -3318785.3525812062;
      ilon = 3.0; ilat = -29.999999999999993 };
    { zone = 31; lon = 5.0; lat = 52.0;
      e = 637294.3658943714; n = 5762926.812914039;
      ilon = 4.999999999999999; ilat = 52.0 };
    { zone = 31; lon = 5.0; lat = -30.0;
      e = 692915.1051785882; n = -3320469.2864978905;
      ilon = 4.999999999999999; ilat = -29.999999999999996 };
    { zone = 53; lon = 135.0; lat = 0.0;
      e = 500000.0; n = 0.0;
      ilon = 135.0; ilat = 0.0 };
    { zone = 53; lon = 135.0; lat = 71.0;
      e = 500000.0; n = 7877396.766691192;
      ilon = 135.0; ilat = 70.99999999999999 };
    { zone = 53; lon = 137.0; lat = 0.0;
      e = 722595.4396756812; n = 0.0;
      ilon = 137.0; ilat = 0.0 };
    { zone = 53; lon = 137.0; lat = 71.0;
      e = 572661.3326799922; n = 7878596.001605914;
      ilon = 137.0; ilat = 70.99999999999999 };
    { zone = 60; lon = 177.0; lat = -30.0;
      e = 500000.00000000244; n = -3318785.3525812062;
      ilon = 177.0; ilat = -29.999999999999993 };
    { zone = 60; lon = 177.0; lat = 71.0;
      e = 500000.00000000093; n = 7877396.766691192;
      ilon = 177.0; ilat = 70.99999999999999 };
    { zone = 60; lon = 179.0; lat = -30.0;
      e = 692915.1051785902; n = -3320469.2864978905;
      ilon = 179.0; ilat = -29.999999999999996 };
    { zone = 60; lon = 179.0; lat = 71.0;
      e = 572661.3326799931; n = 7878596.001605914;
      ilon = 179.0; ilat = 70.99999999999999 };
  ]

let patches =
  [
    { p_lon = 0.5; p_lat = 52.0;
      p_crs =
        "+proj=tmerc +lat_0=0 +lon_0=0.50000000 +k=0.9996 +x_0=500000 +y_0=0 \
         +datum=WGS84 +units=m +no_defs";
      p_lon_in = 0.5; p_lat_in = 52.0;
      p_e = 500000.0; p_n = 5761038.212590415;
      p_ilon = 0.5; p_ilat = 52.0 };
    { p_lon = 0.5; p_lat = 52.0;
      p_crs =
        "+proj=tmerc +lat_0=0 +lon_0=0.50000000 +k=0.9996 +x_0=500000 +y_0=0 \
         +datum=WGS84 +units=m +no_defs";
      p_lon_in = 2.0; p_lat_in = 53.0;
      p_e = 600662.3968058086; p_n = 5873322.9678984955;
      p_ilon = 1.9999999999999996; p_ilat = 52.99999999999999 };
    { p_lon = 0.5; p_lat = -30.0;
      p_crs =
        "+proj=tmerc +lat_0=0 +lon_0=0.50000000 +k=0.9996 +x_0=500000 \
         +y_0=10000000 +datum=WGS84 +units=m +no_defs";
      p_lon_in = 0.5; p_lat_in = -30.0;
      p_e = 500000.0; p_n = 6681214.647418793;
      p_ilon = 0.5; p_ilat = -29.999999999999996 };
    { p_lon = 0.5; p_lat = -30.0;
      p_crs =
        "+proj=tmerc +lat_0=0 +lon_0=0.50000000 +k=0.9996 +x_0=500000 \
         +y_0=10000000 +datum=WGS84 +units=m +no_defs";
      p_lon_in = 2.0; p_lat_in = -29.0;
      p_e = 646108.8085815788; p_n = 6791087.020967786;
      p_ilon = 1.9999999999999993; p_ilat = -29.000000000000004 };
  ]
