#!/usr/bin/env python3
"""Generate the pyproj golden vectors for the Crs tests.

Run from this directory with the geotessera virtualenv, which pins
pyproj 3.7.2:

    /home/avsm2/src/git/avsm/geotessera/.venv/bin/python gen_vectors.py \
        > crs_vectors.ml

The projections are the two the store needs: the northern UTM code a
zone is filed under, used for both hemispheres, and the patch-centred
transverse Mercator of ``geotessera.store._patch_crs``. Every
transformer is built with ``always_xy=True``, the equivalent of PROJ's
``normalize_for_visualization``, so coordinates are longitude first.

"""

from geotessera.store import _patch_crs
from pyproj import Transformer

# Zone centres and a point two degrees east of each, crossed with
# latitudes on both sides of the equator. Southern points go through
# the northern code on purpose: that is the store's convention, and
# their northings come back negative.
ZONES = [1, 30, 31, 53, 60]
LATS = {
    1: [52.0, -55.0],
    30: [52.0, 0.0],
    31: [52.0, -30.0],
    53: [0.0, 71.0],
    60: [-30.0, 71.0],
}

PATCHES = [(0.5, 52.0), (0.5, -30.0)]


def centre_lon(zone):
    return -180.0 + (zone - 0.5) * 6.0


def f(x):
    """A float literal OCaml reads back to the same double."""
    return repr(float(x))


def ocaml_string(s, indent, width=68):
    """*s* as an OCaml string literal wrapped to *width* columns.

    A backslash at end of line swallows the newline and the leading
    blanks of the next line, so the break goes after a space and the
    space stays on the line that is kept.
    """
    lines, cur = [], ""
    for tok in s.split(" "):
        if cur and len(cur) + 1 + len(tok) > width:
            lines.append(cur + " ")
            cur = tok
        else:
            cur = tok if not cur else cur + " " + tok
    lines.append(cur)
    pad = " " * indent
    out = pad + '"' + lines[0]
    for line in lines[1:]:
        out += "\\\n" + pad + " " + line
    return out + '"'


def vector(fwd, inv, lon, lat):
    """Forward from the point, inverse from exactly where it lands."""
    e, n = fwd.transform(lon, lat)
    ilon, ilat = inv.transform(e, n)
    return lon, lat, e, n, ilon, ilat


def rows():
    out = []
    for zone in ZONES:
        crs = f"EPSG:{32600 + zone}"
        fwd = Transformer.from_crs("EPSG:4326", crs, always_xy=True)
        inv = Transformer.from_crs(crs, "EPSG:4326", always_xy=True)
        for dlon in (0.0, 2.0):
            lon = centre_lon(zone) + dlon
            for lat in LATS[zone]:
                out.append((zone,) + vector(fwd, inv, lon, lat))
    return out


def patch_rows():
    out = []
    for plon, plat in PATCHES:
        crs = _patch_crs(plon, plat)
        fwd = Transformer.from_crs("EPSG:4326", crs, always_xy=True)
        inv = Transformer.from_crs(crs, "EPSG:4326", always_xy=True)
        for lon, lat in ((plon, plat), (plon + 1.5, plat + 1.0)):
            out.append((plon, plat, crs) + vector(fwd, inv, lon, lat))
    return out


print("(* Generated by gen_vectors.py, do not edit.  Regenerate with")
print("")
print("     /home/avsm2/src/git/avsm/geotessera/.venv/bin/python \\")
print("       bleeding/tessera/test/geodesy/gen_vectors.py \\")
print("       > bleeding/tessera/test/geodesy/crs_vectors.ml")
print("")
print("   from the repository root, using pyproj 3.7.2.  [e] and [n] are")
print("   where [(lon, lat)] lands, and [ilon] and [ilat] are where")
print("   [(e, n)] comes back to. *)")
print("")
print("type utm = {")
print("  zone : int;")
print("  lon : float;")
print("  lat : float;")
print("  e : float;")
print("  n : float;")
print("  ilon : float;")
print("  ilat : float;")
print("}")
print("")
print("type patch = {")
print("  p_lon : float;")
print("  p_lat : float;")
print("  p_crs : string;")
print("  p_lon_in : float;")
print("  p_lat_in : float;")
print("  p_e : float;")
print("  p_n : float;")
print("  p_ilon : float;")
print("  p_ilat : float;")
print("}")
print("")
print("let utm =")
print("  [")
for zone, lon, lat, e, n, ilon, ilat in rows():
    print(f"    {{ zone = {zone}; lon = {f(lon)}; lat = {f(lat)};")
    print(f"      e = {f(e)}; n = {f(n)};")
    print(f"      ilon = {f(ilon)}; ilat = {f(ilat)} }};")
print("  ]")
print("")
print("let patches =")
print("  [")
for plon, plat, crs, lon, lat, e, n, ilon, ilat in patch_rows():
    print(f"    {{ p_lon = {f(plon)}; p_lat = {f(plat)};")
    print("      p_crs =")
    print(ocaml_string(crs, 8) + ";")
    print(f"      p_lon_in = {f(lon)}; p_lat_in = {f(lat)};")
    print(f"      p_e = {f(e)}; p_n = {f(n)};")
    print(f"      p_ilon = {f(ilon)}; p_ilat = {f(ilat)} }};")
print("  ]")
