(tests
 (names test_release test_link_graph)
 (modules test_release test_link_graph)
 (libraries bushel bushel.eio yamlrw unix))

(test
 (name test_config_releases)
 (modules test_config_releases)
 (libraries bushel.config))

(test
 (name test_forge)
 (modules test_forge)
 (deps
  (glob_files fixtures/*.json))
 (libraries bushel bushel.sync))

(test
 (name test_registries)
 (modules test_registries)
 (deps
  (glob_files fixtures/*.json))
 (libraries bushel bushel.sync ecosystems fetch fetch.mock eio.mock http))

(test
 (name test_releases)
 (modules test_releases)
 (deps
  (glob_files fixtures/*.json))
 (libraries bushel bushel.sync fetch fetch.mock eio.mock))
