(tests
 (names test_release test_link_graph)
 (modules test_release test_link_graph)
 (libraries bushel bushel.eio yamlrw))

(test
 (name test_config_releases)
 (modules test_config_releases)
 (libraries bushel.config))

(test
 (name test_forge)
 (modules test_forge)
 (deps
  (glob_files fixtures/*.json))
 (libraries bushel bushel.sync))
