module C=Imap_eio.Client
module S=Imap_eio.Selected
module E=Imap_eio.Error
let ok=function Ok x -> x | Error e -> failwith (C.error_to_string e)
let u n = match Imap.Uid.of_int64 n with Ok v -> v | Error e -> failwith e
let expect label kind=function
  | Error e when kind e -> ()
  | Error e -> failwith (label ^ ": " ^ C.error_to_string e)
  | Ok _ -> failwith (label ^ ": unexpectedly succeeded")
let state=function E.State _ -> true | _ -> false
let unsupported c = function
  | E.Unsupported x -> Imap.Capability.equal x c | _ -> false
let uncertain=function E.Uncertain _ -> true | _ -> false
let tag n=Printf.sprintf "A%08d" n
let done_ n=tag n ^ " OK done\r\n"
let unhex hex=String.init (String.length hex/2) (fun i ->
  Char.chr (int_of_string ("0x" ^ String.sub hex (2*i) 2)))

(* Generated by Python zlib.compressobj(wbits=-15), one persistent stream,
   Z_SYNC_FLUSH after each server write. Later blocks depend on prior history. *)
let server_block_0=unhex "d252f0f75648cecf2d284a2d2e4e4d51c8cb2fc94ccb4c4e2cc9cccfe3e502000000ffff"
let server_block_1=unhex "d2523054708df00c0e0906b1812aa3433d5dc21c7d3c5d3c4322150c6315ca1273325390e4fc5c2342142c6215f2522b4a78b91c0d20c014245d9c9a939a5c920a540d000000ffff"
let server_block_2=unhex "0299eae61ae2eca1a001d4a260aee0e4ef12191dab506d68606452cbcb55310a46c12818b14013517298814a8eb4d492e40c50c101000000ffff"
let server_block_3=unhex "d2520876750c02961be60815e690b225b108a204000000ffff"
let server_block_4=unhex "82095b80844bf310850e000000ffff"

module Script = struct
  type t={mutable replies:(unit -> string) list;mutable pending:string;
    mutable offset:int;written:Buffer.t;mutable closed:bool}
  let read_methods=[]
  let rec single_read t (buffer @ local)=
    if t.offset=String.length t.pending then (
      match t.replies with
      | [] -> raise End_of_file
      | next::rest -> t.replies<-rest; t.pending<-next (); t.offset<-0;
          single_read t buffer)
    else
      let length=min (Cstruct.length buffer) (String.length t.pending-t.offset) in
      Cstruct.blit_from_string t.pending t.offset buffer 0 length;
      t.offset<-t.offset+length;
      length
  let single_write t (buffers @ local)=
    let buffers=Cstruct.globalize_list buffers in
    List.iter (fun b -> Buffer.add_string t.written (Cstruct.to_string b)) buffers;
    Cstruct.lenv buffers
  let copy t ~src=Eio.Flow.Pi.simple_copy ~single_write t ~src
  let shutdown _ _=()
  let close t=t.closed<-true
end
let handler=Eio.Resource.handler (
  Eio.Resource.H (Eio.Resource.Close,Script.close) ::
  Eio.Resource.bindings (Eio.Flow.Pi.two_way (module Script)))
let script replies={Script.replies;pending="";offset=0;written=Buffer.create 128;closed=false}
let resource raw=Eio.Resource.T (raw,handler)
let reply value ()=value
let with_client ?(caps="IMAP4rev1 UNSELECT COMPRESS=DEFLATE") ?(queued_notice=false) replies f =
  Eio_mock.Backend.run @@ fun () ->
  Eio.Switch.run @@ fun sw ->
  let raw=script ([reply "* OK ready\r\n";
    reply ("* CAPABILITY " ^ caps ^ "\r\n" ^ done_ 1);
    reply (done_ 2);
    reply ("* CAPABILITY " ^ caps ^ "\r\n" ^ done_ 3 ^
      if queued_notice then "* OK queued plaintext notice\r\n" else "")] @ replies) in
  let auth=Imap_eio.Auth.password ~username:"u" ~password:"p"
    ~mechanism:`Login ~allow_insecure_transport:true () in
  let client=ok (C.of_flow ~sw ~auth (resource raw)) in
  let authentication_bytes=Buffer.contents raw.written in
  if not (String.ends_with ~suffix:"A00000003 CAPABILITY\r\n" authentication_bytes) then
    failwith "connection startup unexpectedly activated compression";
  Buffer.clear raw.written;
  Fun.protect ~finally:(fun () -> C.close client) (fun () -> f client raw)

let decode_written raw ~length =
  let prefix="A00000004 COMPRESS DEFLATE\r\n" in
  let bytes=Buffer.contents raw.Script.written in
  if not (String.starts_with ~prefix bytes) then failwith "COMPRESS was not sent in plaintext";
  let encoded=String.sub bytes (String.length prefix) (String.length bytes-String.length prefix) in
  let input=script [reply encoded] in
  let codec=Imap_eio_core.Deflate_flow.create (resource input) in
  Fun.protect ~finally:(fun () -> Imap_eio_core.Deflate_flow.close codec) (fun () ->
    let output=Cstruct.create length in
    let rec read offset=
      if offset<length then
        let count=Imap_eio_core.Deflate_flow.read codec (Cstruct.sub output offset (length-offset)) in
        read (offset+count) in
    read 0;
    Cstruct.to_string output)

let test_coalesced_and_fragmented () =
  List.iter (fun fragmented ->
    let replies=[reply ("* OK inline plaintext notice\r\n" ^ done_ 4 ^ server_block_0)] in
    let remaining=server_block_1 ^ server_block_2 ^ server_block_3 ^ server_block_4 in
    let replies=replies @ if fragmented then
      List.init (String.length remaining) (fun i -> reply (String.make 1 remaining.[i]))
      else [reply remaining] in
    with_client ~queued_notice:true replies (fun client raw ->
      ok (C.compress_deflate client);
      let written=Buffer.length raw.written in
      expect "second COMPRESS" state (C.compress_deflate client);
      if Buffer.length raw.written<>written then failwith "second COMPRESS was sent";
      let sink=Buffer.create 1024 in
      ok (C.with_mailbox client ~mode:`Read_only "INBOX" (fun selected ->
        ok (S.fetch_to selected ~uid:(u 7L) (Eio.Flow.buffer_sink sink));
        if List.map Imap.Uid.to_int64 (ok (S.uid_search selected "ALL"))<>[7L]
        then failwith "compressed SEARCH result lost";
        Ok ()));
      if Buffer.contents sink<>String.make 1024 'x' then failwith "compressed literal changed";
      let expected="A00000005 EXAMINE INBOX\r\n" ^
        "A00000006 UID FETCH 7 (UID BODY.PEEK[])\r\n" ^
        "A00000007 UID SEARCH ALL\r\nA00000008 UNSELECT\r\n" in
      if decode_written raw ~length:(String.length expected)<>expected then
        failwith "compressed client commands changed")) [false;true]

let test_refusal_reusable () =
  List.iter (fun (status,wire,code) ->
    with_client [reply (tag 4 ^ " " ^ status ^ " " ^ wire ^ "refused\r\n");reply (done_ 5)]
      (fun client raw ->
        expect "COMPRESS rejection code" (function
          | E.Rejected {code=actual;_} -> actual=code | _ -> false)
          (C.compress_deflate client);
        ok (C.create_mailbox client ~mailbox:"Draft");
        if Buffer.contents raw.written<>
           "A00000004 COMPRESS DEFLATE\r\nA00000005 CREATE Draft\r\n" then
          failwith "rejected compression changed plaintext framing"))
    ["NO","[COMPRESSIONACTIVE] ",Some Imap.Response.Compressionactive;
     "BAD","",None];
  with_client ~caps:"IMAP4rev1 UNSELECT" [] (fun client raw ->
    expect "COMPRESS capability required"
      (unsupported (Imap.Capability.Compress `Deflate))
      (C.compress_deflate client);
    if Buffer.length raw.written<>0 then failwith "unadvertised COMPRESS sent")

let test_malformed_and_uncertain () =
  List.iter (fun mutation ->
    with_client [reply (done_ 4 ^ "\007")] (fun client raw ->
      ok (C.compress_deflate client);
      if mutation then expect "compressed mutation remains uncertain" uncertain
          (C.create_mailbox client ~mailbox:"Draft")
      else expect "malformed compressed stream" (function
        | E.Transport _ | E.Protocol _ -> true | _ -> false)
          (C.with_mailbox client ~mode:`Read_only "INBOX" (fun _ -> Ok ()));
      if C.is_open client || not raw.closed then failwith "malformed stream remained reusable"))
    [false;true]

let test_cancelled_handshake () =
  let entered,mark_entered=Eio.Promise.create () in
  with_client [reply "* OK before COMPRESS completion\r\n";
    (fun () -> Eio.Promise.resolve mark_entered ();Eio.Fiber.await_cancel ())]
    (fun client raw ->
      Eio.Fiber.first
        (fun () -> ignore (C.compress_deflate client))
        (fun () -> Eio.Promise.await entered);
      if C.is_open client || not raw.closed then failwith "cancelled compression stayed open";
      if Buffer.contents raw.written<>"A00000004 COMPRESS DEFLATE\r\n" then
        failwith "cancelled compression replayed");
  with_client [] (fun client raw ->
    C.close client;
    expect "closed compression" (function E.Closed -> true | _ -> false)
      (C.compress_deflate client);
    if Buffer.length raw.written<>0 then failwith "closed compression wrote bytes")

let test_decompressed_budget () =
  let module E = Imap_eio_core.Error in
  let ok = function Ok x -> x | Error _ -> failwith "internal compression failed" in
  let expect label kind = function
    | Error e when kind e -> ()
    | _ -> failwith label in
  Eio_mock.Backend.run @@ fun () ->
  let encoded=unhex "d252f0f756a81805a360148c8251300a46c18803bc5c8e061060046a0ea4e4e7a5f27201000000ffff" in
  let raw=script [reply (done_ 1 ^ encoded)] in
  let transport=Imap_eio_core.Transport.of_flow (resource raw) in
  let session=Imap_eio_core.Session.create ~max_metadata:1024
    ~max_command_metadata:4096 transport in
  session.capabilities<-
    Imap.Capability.(Set.of_list [Compress `Deflate]);
  ok (Imap_eio_core.Session.protect session (fun () -> Imap_eio_core.Session.compress_deflate session));
  expect "decompressed metadata budget" (function E.Limit _ -> true | _ -> false)
    (Imap_eio_core.Session.protect session (fun () ->
      ignore (Imap_eio_core.Session.command session "NOOP")));
  if not raw.closed then failwith "decompressed budget failure kept stream open"

let test_cancelled_compressed_read () =
  let entered,mark_entered=Eio.Promise.create () in
  with_client [reply (done_ 4);
    (fun () -> Eio.Promise.resolve mark_entered ();Eio.Fiber.await_cancel ())]
    (fun client raw ->
      ok (C.compress_deflate client);
      Eio.Fiber.first
        (fun () -> ignore (C.with_mailbox client ~mode:`Read_only "INBOX"
          (fun _ -> Ok ())))
        (fun () -> Eio.Promise.await entered);
      if C.is_open client || not raw.closed then
        failwith "cancelled compressed read kept connection open")

let () =
  test_coalesced_and_fragmented ();test_refusal_reusable ();
  test_malformed_and_uncertain ();test_cancelled_handshake ();
  test_decompressed_budget ();test_cancelled_compressed_read ()
