(test
 (name test_auth)
 (modules test_auth)
 (libraries spindle jsont jsont.bytesrw)
 (deps auth-fixtures.json))

(executable
 (name slow_server)
 (modules slow_server)
 (libraries spindle eio_main))

(test
 (name test_store)
 (modules test_store)
 (libraries spindle eio_main))

(test
 (name test_events)
 (modules test_events)
 (libraries spindle eio_main))

(test
 (name test_catalog)
 (modules test_catalog)
 (libraries spindle eio_main))

(test
 (name test_runner)
 (modules test_runner)
 (libraries spindle eio_main))

(test
 (name test_operations)
 (modules test_operations)
 (libraries spindle eio_main))

(executable
 (name tangled_server)
 (modules tangled_server)
 (libraries spindle eio_main))
