(library
 (name bloscz)
 (public_name bloscz)
 (libraries base_bigstring)
 (foreign_stubs
  (language c)
  (names bloscz_stubs)
  (flags
   (:standard)
   (:include c_flags.sexp)))
 (c_library_flags
  (:include c_library_flags.sexp)))

(rule
 (targets c_flags.sexp c_library_flags.sexp)
 (action
  (run ./config/discover.exe)))
