when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - shell
    - stdenv
    - findutils
    - binutils
    - libunwind
    - ncurses
    - opam
    - git
    - gawk
    - gnupatch
    - gnum4
    - gnumake
    - gnutar
    - gnused
    - gnugrep
    - diffutils
    - gzip
    - bzip2
    - gcc
    - ocaml
    - pkg-config

steps:
  - name: opam
    command: |
       opam init --disable-sandboxing -a -y
  - name: repo
    command: |
       opam repo add aoah https://tangled.org/anil.recoil.org/aoah-opam-repo.git
  - name: switch
    command: |
       export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(nix build nixpkgs#gmp.dev --no-link --print-out-paths)/lib/pkgconfig"
       opam install . --confirm-level=unsafe-yes --deps-only
  - name: build
    command: |
       opam exec -- dune build -p requests
  - name: switch-test
    command: |
       opam install . --confirm-level=unsafe-yes --deps-only --with-test
  - name: test
    command: |
       echo skipping tests until we can httpbin
  - name: doc
    command: |
       opam install -y odoc
       opam exec -- dune build @doc
