module P = Matrix_client.Olm_dehydrated_pickle
module O = Matrix_client.Olm
module Ck = Matrix_client.Crypto_key
module R = Matrix_client.Random
module Id = Matrix_proto.Id
module Smap = Map.MakePortable (String)

let random =
  R.of_source
    (Eio.Flow.string_source
       (String.init 65536 (fun i -> Char.chr (((i * 71) + 19) land 255))))

let jstring_esc s =
  let b = Buffer.create (String.length s + 2) in
  Buffer.add_char b '"';
  String.iter
    (fun c ->
      match c with
      | '"' -> Buffer.add_string b "\\\""
      | '\\' -> Buffer.add_string b "\\\\"
      | '\n' -> Buffer.add_string b "\\n"
      | c when Char.code c < 0x20 ->
          Buffer.add_string b (Printf.sprintf "\\u%04x" (Char.code c))
      | c -> Buffer.add_char b c)
    s;
  Buffer.add_char b '"';
  Buffer.contents b

let json_map s =
  match
    Jsont_bytesrw.decode_string
      (Matrix_proto.Json.Codec.as_string_map Matrix_proto.Json.Codec.json)
      s
  with
  | Ok x -> x
  | Error e -> Alcotest.fail e

let json_string x =
  match Jsont.Json.decode Matrix_proto.Json.Codec.string x with
  | Ok s -> s
  | Error e -> Alcotest.failf "oracle field was not a string: %s" e

let json_int x =
  match Jsont.Json.decode Matrix_proto.Json.Codec.int x with
  | Ok n -> n
  | Error e -> Alcotest.failf "oracle field was not an integer: %s" e

let field m name =
  match Smap.find_opt name m with
  | Some x -> x
  | None -> Alcotest.failf "oracle response lacks %s" name

let cmd name fields =
  "{" ^ jstring_esc "cmd" ^ ":" ^ jstring_esc name
  ^ (if fields = [] then "" else ",")
  ^ String.concat "," (List.map (fun (k, v) -> jstring_esc k ^ ":" ^ v) fields)
  ^ "}"

type oracle = { ic : in_channel; oc : out_channel }

let oracle_path () =
  match Sys.getenv_opt "VODOZEMAC_ORACLE" with
  | Some p when Sys.file_exists p -> Some p
  | _ ->
      let rel =
        Filename.concat "test"
          (Filename.concat "vodozemac-oracle"
             (Filename.concat "target"
                (Filename.concat "release" "vodozemac-oracle")))
      in
      let rec up dir n =
        if n = 0 then None
        else
          let p = Filename.concat dir rel in
          if Sys.file_exists p then Some p
          else
            let parent = Filename.dirname dir in
            if parent = dir then None else up parent (n - 1)
      in
      up (Sys.getcwd ()) 8

let call o request =
  output_string o.oc request;
  output_char o.oc '\n';
  flush o.oc;
  let response =
    try input_line o.ic with End_of_file -> Alcotest.fail "oracle exited"
  in
  let fields = json_map response in
  match Smap.find_opt "ok" fields with
  | Some x when Jsont.Json.decode Jsont.bool x = Ok true -> fields
  | _ -> Alcotest.failf "oracle error: %s" response

let b64 s = Matrix_proto.Base64.encode s
let raw_key = String.init 32 (fun i -> Char.chr (i + 1))
let device = Id.Device_id.of_string_exn "DEHYDRATED"

(* Generated by vodozemac 0.9's [Account::to_libolm_pickle] after creating
   three one-time keys, one fallback key, and marking both sets published. It
   makes the compatibility gate run even when the optional oracle binary has
   not been built. *)
let rust_fixture_pickle =
  "ky1aB6HNXrnNfK6wVyyeCf9OJOf8TtEG/o60p8QLpJl94rEq4uIeVASTEiQfsB2RiJDqFt32HAqNwIK9hUQF3+uClo+bptas2dRYQzZVPzMvni4LfD26yTfdz6EEcURE26vQH1PiGuguU4GllkPO6HfBXsbL1AiZLJYIcawwGBjfJ8z2QVj72TDfkzgIW4jFuAgK6ivN23hZQNbVBjF6kESbYhGIEXim8DvCW45rNz7gcQY5JXyv6Ds1Oq5qb5TAhULUXbR2kr62uyViUIbFCdj5C5d8wP7WIrV5FxIYx3vhl5aw0WtW90BNYpVrbLA7JEama3EaC/WlFZa2Fnpx3m3N8+05Mxnk6DuQTZCBO5d0klc6LaR3LREX8AT4wszMi+1f5iO9i10ELQeT/inpXf0tWGHLPA9gAeRWRAg3osCNJNtlaTw2ytj2qAtWoIQjiSxxzyC7q4WE08cn9r0Q2NgHG0fHfrWj++cypPyIDA8c+TS7cIlqcckNF/D16g9JmWP+5oTM1O/PNuaIKfoxhDIFp+aHQzD4u+GKrzowwzd80aOeiixEZSYflFMWYu1utmXWpTZxBjctUfuITyKEzLBoB8AFzenvafFJLMD/sByqEVTKnYFo+w"

let rust_fixture_ed25519 = "89KmKr7cO6QopEebo21OB0mVSX2zVey/+0WgjnZFwQ4"
let rust_fixture_curve25519 = "M1VBzmfHDNYyWo8QETuQJaWsPwIuIpC6bDEBsLjvazI"

let rust_fixture_otks =
  [
    ("AAAAAAAAAAA", "sSuG/IV+5BHptRL5QGX54v8HAohXuvS+jkS8zdUMOjE");
    ("AAAAAAAAAAE", "nT9hRycU+aTKSTDyBi1BXSKm61CDemGtZYcURmNRAVQ");
    ("AAAAAAAAAAI", "dXZCh6dvPUsnvmB5VfJiG2o4jhbS9CTzNVIawc7dITU");
  ]

let account_otks account =
  O.Account.one_time_keys account
  |> List.map (fun (id, key) ->
      (Ck.Key_id.id id, Ck.Curve25519.Public.to_base64 key))
  |> List.sort compare

let test_rust_fixture () =
  let decoded =
    match
      P.unpickle ~device_id:device ~pickle_key:raw_key rust_fixture_pickle
    with
    | Ok value -> value
    | Error (`Msg message) -> Alcotest.fail message
  in
  Alcotest.(check string)
    "fixture Ed25519" rust_fixture_ed25519
    (Ck.Ed25519.Public.to_base64 (O.Account.ed25519_key decoded.account));
  Alcotest.(check string)
    "fixture Curve25519" rust_fixture_curve25519
    (Ck.Curve25519.Public.to_base64 (O.Account.curve25519_key decoded.account));
  Alcotest.(check (list (pair string string)))
    "fixture one-time keys" rust_fixture_otks
    (account_otks decoded.account);
  Alcotest.(check (list string))
    "published fixture OTK IDs"
    (List.map fst rust_fixture_otks)
    (decoded.published_one_time_keys |> List.map Ck.Key_id.id
   |> List.sort String.compare);
  Alcotest.(check (list string))
    "published fixture fallback ID" [ "AAAAAAAAAAA" ]
    (List.map Ck.Key_id.id decoded.published_fallback_keys);
  let message = "recorded Rust pickle still signs" in
  let signature = O.Account.sign decoded.account message in
  Alcotest.(check bool)
    "expanded fixture key signs" true
    (Ck.Ed25519.Public.verify
       (O.Account.ed25519_key decoded.account)
       ~signature ~data:message)

let test_high_bit_key_id () =
  let original = O.Account.create ~random () in
  O.Account.generate_one_time_keys ~random original 1;
  let pickle = O.Account.to_pickle original in
  let key = List.hd pickle.stored_one_time_keys in
  let high_id = "AAAAAIAAAAA" in
  let account =
    O.Account.of_pickle
      {
        pickle with
        stored_one_time_keys = [ { key with key_id = high_id } ];
        next_key_id = 0x80000001;
      }
  in
  let encoded =
    Result.get_ok (P.pickle ~device_id:device ~pickle_key:raw_key account)
  in
  let decoded =
    Result.get_ok (P.unpickle ~device_id:device ~pickle_key:raw_key encoded)
  in
  Alcotest.(check (list string))
    "u32 ID is zero-extended" [ high_id ]
    (O.Account.one_time_key_ids decoded.account |> List.map Ck.Key_id.id)

let test_roundtrip () =
  let account = O.Account.create ~random () in
  O.Account.generate_one_time_keys ~random account 3;
  O.Account.generate_fallback_key ~random account;
  let value =
    match
      P.pickle
        ~is_published:(fun _ -> true)
        ~device_id:device ~pickle_key:raw_key account
    with
    | Ok x -> x
    | Error (`Msg m) -> Alcotest.fail m
  in
  let d =
    match P.unpickle ~device_id:device ~pickle_key:raw_key value with
    | Ok x -> x
    | Error (`Msg m) -> Alcotest.fail m
  in
  Alcotest.(check string)
    "identity"
    (Ck.Ed25519.Public.to_base64 (O.Account.ed25519_key account))
    (Ck.Ed25519.Public.to_base64 (O.Account.ed25519_key d.account));
  Alcotest.(check int) "otk count" 3 (O.Account.one_time_keys_count d.account);
  Alcotest.(check int)
    "published OTK count" 3
    (List.length d.published_one_time_keys);
  Alcotest.(check int)
    "published fallback count" 1
    (List.length d.published_fallback_keys)

let test_rejects () =
  let account = O.Account.create ~random () in
  let value =
    match P.pickle ~device_id:device ~pickle_key:raw_key account with
    | Ok x -> x
    | Error (`Msg m) -> Alcotest.fail m
  in
  let bad_device = Id.Device_id.of_string_exn "OTHER" in
  let bad s =
    match P.unpickle ~device_id:device ~pickle_key:raw_key s with
    | Ok _ -> false
    | Error _ -> true
  in
  Alcotest.(check bool)
    "wrong key" true
    (match
       P.unpickle ~device_id:device ~pickle_key:(String.make 32 'x') value
     with
    | Ok _ -> false
    | Error _ -> true);
  Alcotest.(check bool)
    "wrong device" true
    (match P.unpickle ~device_id:bad_device ~pickle_key:raw_key value with
    | Ok _ -> false
    | Error _ -> true);
  let tampered =
    String.mapi
      (fun i c -> if i = 3 then Char.chr (Char.code c lxor 1) else c)
      value
  in
  Alcotest.(check bool) "tamper" true (bad tampered);
  Alcotest.(check bool)
    "truncation" true
    (bad (String.sub value 0 (String.length value - 2)))

let test_oracle () =
  match oracle_path () with
  | None -> Printf.printf "SKIP vodozemac oracle not built\n%!"
  | Some path ->
      let ic, oc = Unix.open_process_args path [| path |] in
      let o = { ic; oc } in
      Fun.protect
        ~finally:(fun () -> ignore (Unix.close_process (ic, oc)))
        (fun () ->
          let created =
            call o (cmd "create_account" [ ("one_time_keys", "3") ])
          in
          let account = json_int (field created "account") in
          ignore
            (call o
               (cmd "generate_fallback_key"
                  [ ("account", string_of_int account) ]));
          let picked =
            call o
              (cmd "account_pickle"
                 [
                   ("account", string_of_int account);
                   ("pickle_key", jstring_esc (b64 raw_key));
                   ("device_id", jstring_esc (Id.Device_id.to_string device));
                 ])
          in
          let rust_pickle = json_string (field picked "pickle") in
          let decoded =
            match
              P.unpickle ~device_id:device ~pickle_key:raw_key rust_pickle
            with
            | Ok x -> x
            | Error (`Msg m) -> Alcotest.failf "Rust pickle: %s" m
          in
          let rust_ed = json_string (field created "ed25519") in
          Alcotest.(check string)
            "Rust pickle identity" rust_ed
            (Ck.Ed25519.Public.to_base64
               (O.Account.ed25519_key decoded.account));
          Alcotest.(check int)
            "Rust pickle OTKs" 3
            (O.Account.one_time_keys_count decoded.account);
          let message = "legacy expanded signing" in
          let signature =
            Ck.Signature.to_base64 (O.Account.sign decoded.account message)
          in
          ignore
            (call o
               (cmd "ed25519_verify"
                  [
                    ("key", jstring_esc rust_ed);
                    ("message", jstring_esc message);
                    ("signature", jstring_esc signature);
                  ]));
          let local =
            match
              P.pickle
                ~is_published:(fun _ -> true)
                ~device_id:device ~pickle_key:raw_key decoded.account
            with
            | Ok x -> x
            | Error (`Msg m) -> Alcotest.fail m
          in
          let reply =
            call o
              (cmd "account_from_pickle"
                 [
                   ("pickle", jstring_esc local);
                   ("pickle_key", jstring_esc (b64 raw_key));
                   ("device_id", jstring_esc (Id.Device_id.to_string device));
                 ])
          in
          Alcotest.(check string)
            "OCaml pickle identity" rust_ed
            (json_string (field reply "ed25519"));
          let signed =
            call o
              (cmd "account_sign_from_pickle"
                 [
                   ("pickle", jstring_esc local);
                   ("pickle_key", jstring_esc (b64 raw_key));
                   ("device_id", jstring_esc (Id.Device_id.to_string device));
                   ("message", jstring_esc message);
                 ])
          in
          let rust_signature = json_string (field signed "signature") in
          Alcotest.(check string)
            "expanded-key signatures agree" signature rust_signature;
          let rust_signature =
            Result.get_ok (Ck.Signature.of_base64 rust_signature)
          in
          Alcotest.(check bool)
            "OCaml verifies Rust restored signature" true
            (Ck.Ed25519.Public.verify
               (O.Account.ed25519_key decoded.account)
               ~signature:rust_signature ~data:message))

let () =
  Alcotest.run "dehydrated pickle"
    [
      ( "codec",
        [
          Alcotest.test_case "roundtrip" `Quick test_roundtrip;
          Alcotest.test_case "recorded Rust fixture" `Quick test_rust_fixture;
          Alcotest.test_case "high-bit key ID" `Quick test_high_bit_key_id;
          Alcotest.test_case "rejects" `Quick test_rejects;
        ] );
      ("vodozemac", [ Alcotest.test_case "bidirectional" `Quick test_oracle ]);
    ]
