(tests
 (names
  test_route
  test_req
  test_multipart
  test_conditional
  test_resp
  test_mime
  test_static
  test_cache
  test_negotiate
  test_wrappers
  test_media
  test_sse)
 (modules
  test_route
  test_req
  test_multipart
  test_conditional
  test_resp
  test_mime
  test_static
  test_cache
  test_negotiate
  test_wrappers
  test_media
  test_sse)
 (package proffer)
 (libraries proffer proffer_mock))

(test
 (name test_httpz)
 (modules test_httpz)
 (package proffer-httpz)
 (libraries proffer proffer_httpz eio eio_main))

(test
 (name test_config)
 (modules test_config)
 (package proffer-httpz)
 (libraries proffer proffer_httpz eio_main))
