(lang dune 3.21)
(name imap)
(generate_opam_files true)
(license ISC)
(authors "Anil Madhavapeddy <anil@recoil.org>")
(maintainers "Anil Madhavapeddy <anil@recoil.org>")
(package
 (name imap)
 (synopsis "IMAP protocol and Eio client for OCaml")
 (depends
  (ocaml (>= 5.2))
  mail-flag
  maildir
  eio
  eio_main
  tls
  tls-eio
  x509
  ca-certs
  cstruct
  domain-name
  ipaddr
  mirage-crypto-rng
  base64
  decompress
  sqlite3-eio
  digestif
  cmdliner
  (alcotest :with-test)))
